### ISSUE TITLE
[add] 3차 세미나 과제

### ISSUE THREAD

**Issue by hyejungg** [30th-THE-SOPT-Server-Part/HyeJung#5]
## 📌 Feature Issue
- 세미나에서 나온 코드들 직접 타이핑 하면서 익혀보기
- 세미나 실습 폴더 내부에 Blog.ts Model 을 만들고 CRUD 완성하기

## 📝 To-do

🌼 실천과제

- [x] 견고한 Node.js 프로젝트 설계
- [x] CRUD 실습

🌻 발전과제
- API 설계 및 구현
- [x] [POST] /blog
```
request : 
body {
  userId: ~, 
  title: '서버 3차 세미나', 
  tag: {
    'sopt',
    'seminar',
    'server',
    'express',
    'node',
    'mongoDB',
    'typescript'
  },
  description: '이번 주차에서는 견고한 Nodejs 프로젝트 설계 및 NoSQL에 대해서 배웠습니다.'
}
response:
{
   status: 201,
   success: true, 
   message: '블로그 게시 성공하였습니다.',
   data: {post_id}
}
```
- [x] [PUT] /blog/:postId
```
request : 
body {
  userId: ~, 
  title: '서버 3차 세미나 수정', 
  tag: {
    'sopt',
    'server',
    'express',
    'node',
    'mongoDB',
    'typescript'
  },
  description: '이번 주차에서는 견고한????? Nodejs 프로젝트 설계 및 NoSQL에 대해서 배웠습니다.'
}
response:
204 NoContents
```
- [x] [GET] /blog/:postId
```
response:
{
   status: 200,
   success: true, 
   message: '블로그 조회 성공하였습니다.'
   data: {
  title: '서버 3차 세미나 수정', 
  tag: {
    'sopt',
    'server',
    'express',
    'node',
    'mongoDB',
    'typescript'
  },
  description: '이번 주차에서는 견고한????? Nodejs 프로젝트 설계 및 NoSQL에 대해서 배웠습니다.'
}
}
```
- [x] [DELETE] /blog/:postId
```
response:
204 NoContents
```
