### ISSUE TITLE
[FEAT] 4차 세미나 과제

### ISSUE THREAD

**Issue by hyejungg** [30th-THE-SOPT-Server-Part/HyeJung#9]
## 📌 Feature Issue
- AWS EC2와 S3를 이해하고, API 실습 따라가기

## 📝 To-do

🌼 실천과제

- [x] 라이브 코딩 따라가기

🌻 발전과제

- [x] Movie Collection CRUD API 만들기
- [x] User부분에 express-validator 붙이기
